### ISSUE TITLE
Remove the real-time counting of A, T, G, C.

### ISSUE THREAD

**Issue by gbelwariar** [gbelwariar/Microbiome-Diversity-Inspector#12]
@MAZHARMIK - I think we should remove showing the texts - 
"
The number of A's are - XXXX
The number of T's are - XXXX
The number of G's are - XXXX
The number of C's are - XXXX
"
which comes when we upload a FASTA/FASTQ file for entropy analysis.

**Comment by MAZHARMIK** [comment]
Yes, you are right. I will soon have a look at it.

**Comment by gbelwariar** [comment]
Thanks.

**Comment by MAZHARMIK** [comment]
This issue has been fixed. But I will add the changes here after I merge your PRs. SO, for now I am closing this issue. 
Thanks

**Comment by gbelwariar** [comment]
Ok sure, thanks.

**Comment by gbelwariar** [comment]
This was fixed in c9444e1158ede889444260fb7fef11029f606dce
