### ISSUE TITLE
File name shown while converting files is getting hidden due to the dark background animation.

### ISSUE THREAD

**Issue by gbelwariar** [gbelwariar/Microbiome-Diversity-Inspector#14]
After the file is uploaded for conversion from FASTQ to FASTA, then the file name shown (note that this is visible to the users only when the file uploaded is big enough due to the large processing time).

@MAZHARMIK  - Also can you check similarly for FASTA to FASTQ conversion?

Please find the attached screenshot showing the issue -

![screenshot](https://user-images.githubusercontent.com/14831291/34971615-c37e1992-faa1-11e7-9692-d0febcf5cf1d.GIF)

**Comment by MAZHARMIK** [comment]
Ok I got it. I will get it fixed soon. Thanks for pointing it out.

**Comment by gbelwariar** [comment]
Thanks.

**Comment by MAZHARMIK** [comment]
Issue fixed.
