### ISSUE TITLE
Improve the UI design of the SRR-accession number input text.

### ISSUE THREAD

**Issue by gbelwariar** [gbelwariar/Microbiome-Diversity-Inspector#20]
@MAZHARMIK - Do you think that having a "round border of the input text" would look better than the current design? Also feel free to make other UI improvements.

I am attaching the screenshot again below.
Thanks.

![screenshot](https://user-images.githubusercontent.com/14831291/35101927-4da7381a-fc87-11e7-9389-e7c030d07d37.GIF)

**Comment by MAZHARMIK** [comment]
Yes, I think some changes can be done to make it look a bit organized. I will soon update it and let you know. 
Thanks

**Comment by gbelwariar** [comment]
Thanks. Can you also remove the redundant styles remaining in the stylesheet after removing the real-time counting in this PR - https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/22?

**Comment by MAZHARMIK** [comment]
Yes I have removed them. Let me cross check

**Comment by MAZHARMIK** [comment]
Yes, I think I have removed them all. You may have a look

**Comment by gbelwariar** [comment]
Yes, you have removed them. Thanks.

**Comment by MAZHARMIK** [comment]
Issue fixed. You may have a look and do let me know if there is anything else we can change. Thanks
