### ISSUE TITLE
Entropy value shown after analysis is much smaller than other texts on the page.

### ISSUE THREAD

**Issue by gbelwariar** [gbelwariar/Microbiome-Diversity-Inspector#21]
See the screenshot below-

![screenshot](https://user-images.githubusercontent.com/14831291/35163048-64661032-fd6b-11e7-9c19-3a167f93f7ca.GIF)

**Comment by MAZHARMIK** [comment]
Fixed.

**Comment by gbelwariar** [comment]
This was fixed in 1f4f5dc
