### ISSUE TITLE
Show the real-time entropy analysis below the section of "Entropy Analysis" instead of showing at the bottom?

### ISSUE THREAD

**Issue by gbelwariar** [gbelwariar/Microbiome-Diversity-Inspector#31]
Currently, the real-time plotting of "Entropy vs Time" happens at the bottom of the page, but I think it would be better to show it just below where there is the option to upload a file for entropy analysis.
@MAZHARMIK - Let me know your thoughts on this.

**Comment by MAZHARMIK** [comment]
Yes you are right. As it is displayed at the bottom, so it seems that nothing is getting processed.

**Comment by MAZHARMIK** [comment]
The issue has been resolved. I have committed it ok. You may have a look at it.
