### ISSUE TITLE
Change the "Download MetaSub data" layout.

### ISSUE THREAD

**Issue by gbelwariar** [gbelwariar/Microbiome-Diversity-Inspector#37]
@MAZHARMIK - I am creating this issue since you pointed out today that "Download MetaSub data" layout (See the screenshot below) could be enhanced further. Feel free to close this issue if you believe that no further change is required.

![screenshot](https://user-images.githubusercontent.com/14831291/35320393-a6115eb4-0109-11e8-9464-bfff48c0aa56.GIF)

**Comment by MAZHARMIK** [comment]
Yes, I have fixed it. It was just a small change so I have commited the change ok.

**Comment by gbelwariar** [comment]
:+1:
