### ISSUE TITLE
Add screenshots of the tool in README.

### ISSUE THREAD

**Issue by gbelwariar** [gbelwariar/Microbiome-Diversity-Inspector#59]
This will help the new users understand and relate with the tool better.

**Comment by gbelwariar** [comment]
@MAZHARMIK - Assigning you as well, so that if you get some free time, then you can go ahead and close this issue. Otherwise, I will do this at some point or the other. This issue needs to be resolved before giving reference to this repository in any public research paper/publication since the README dictates the content of the [official website](https://gbelwariar.github.io/Microbiome-Diversity-Inspector/) of this repository.

**Comment by MAZHARMIK** [comment]
Ok sure. I will do it today.

**Comment by gbelwariar** [comment]
Thanks.

**Comment by gbelwariar** [comment]
This was resolved in https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/83
