### ISSUE TITLE
Adding my API key as well for ease fo access to multiple files

### ISSUE THREAD

**Issue by MAZHARMIK** [gbelwariar/Microbiome-Diversity-Inspector#63]
If possible you can also add my API key in the documentation so that we don't have to find it everytime.
API: 2e1d9b1d5c8d4053addd1ca8c3a0ecba

**Comment by gbelwariar** [comment]
Thanx. I have replaced my API key with yours. Point your browser to https://docs.google.com/document/d/e/2PACX-1vQHX_-TCCtYtODA4xQgCnc5GtjeOP8sy08JE5spjB1usOiGmyPsriQoRr2U4IsJfFC1rJiFIlJYS-Za/pub to see the change.
