### ISSUE TITLE
Divider missing after "Download MetaSUB data" card.

### ISSUE THREAD

**Issue by gbelwariar** [gbelwariar/Microbiome-Diversity-Inspector#64]
@MAZHARMIK - Just wanted to inquire, whether we should add another divider between "Download MetaSUB data" card and "Entropy Analysis" section as you did in https://github.com/gbelwariar/Microbiome-Diversity-Inspector/pull/62?

**Comment by MAZHARMIK** [comment]
Yes. I will check it first and get it done. Thanks for pointing it out.

**Comment by gbelwariar** [comment]
Thanks.

**Comment by MAZHARMIK** [comment]
It has been resolved. You may have a look at it. Thanks
