### ISSUE TITLE
Divider at the wrong position after entropy-analysis.

### ISSUE THREAD

**Issue by gbelwariar** [gbelwariar/Microbiome-Diversity-Inspector#65]
How to reproduce this issue? - Upload a file for entropy analysis.

Screenshot - 

![screenshot](https://user-images.githubusercontent.com/14831291/35622549-3b605584-06ae-11e8-9292-b4e9144bb133.GIF)

@MAZHARMIK - Instead of creating a divider after each text with style - 'open-sans-sans-serif-text' (as you have done in this PR - https://github.com/gbelwariar/Microbiome-Diversity-Inspector/commit/4d869c7b61ad78bacee680e05cca55873ec393fd), maybe you can use **\<hr\>** tags and associate them with a CSS selector (for an example, see - https://codepen.io/ibrahimjabbari/pen/ozinB).
This would also fix [this issue](https://github.com/gbelwariar/Microbiome-Diversity-Inspector/issues/64) easily.

**Comment by MAZHARMIK** [comment]
Resolved
