### ISSUE TITLE
Two dividers showing when converting a FASTA/Q file to FASTQ/A respectively.

### ISSUE THREAD

**Issue by gbelwariar** [gbelwariar/Microbiome-Diversity-Inspector#66]
How to reproduce this issue? - Upload a big enough FASTQ file for conversion to FASTA or a big enough FASTA and QUAL file for conversion to FASTQ.

Screenshot - 

![screenshot](https://user-images.githubusercontent.com/14831291/35625690-4511a618-06b9-11e8-8149-ce4d9eeb35a9.GIF)

There are two dividers - one below the text - ***'Convert FASTQ to FASTA'*** and another below ***'Converting XXX.fastq...'*** but I think we should show only one divider, below ***'Converting XXX.fastq...'*** - if the file is in the process of conversion otherwise below ***'Convert FASTQ to FASTA'*** - when no file is uploaded for conversion. The same problem is there with the FASTA + QUAL to FASTQ conversion. 

Let me know your thoughts on this. I have suggested a possible fix earlier in https://github.com/gbelwariar/Microbiome-Diversity-Inspector/issues/65.

**Comment by MAZHARMIK** [comment]
Resolved
